import react from 'react';
import Head from 'next/head';
function Header() 
{
    return(
   <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* <!-- MDB --> */}
<script
  type="text/javascript"
  src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.js"
></script>
        {/* <!-- Font Awesome --> */}
<link
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
  rel="stylesheet"
/>
{/* <!-- Google Fonts --\ */}
<link
  href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
  rel="stylesheet"
/>
{/* <!-- MDB --> */}
<link
  href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.css"
  rel="stylesheet"
/>
      </Head> 
       <div>
           <i></i>
       </div>
       <header className="header">
           <div id="logo-div">
           <img className="logo" src="https://savvyschool.edu.pk/img/savvy%20designs/savvy-logo.png" alt="shaur logo" />
           <p>Shaur Educational <br /> Complex</p>
           </div>
           <div>
           <nav style={{height: '50px',width:'900px',boxShadow:'none',display:'flex',justifyContent:'center'}} class="navbar navbar-expand-lg navbar-light bg-light">
  {/* <!-- Container wrapper --> */}
  <div class="container-fluid">
    {/* <!-- Toggle button --> */}
    <button
      class="navbar-toggler"
      type="button"
      data-mdb-toggle="collapse"
      data-mdb-target="#navbarLeftAlignExample"
      aria-controls="navbarLeftAlignExample"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <i class="fas fa-bars"></i>
    </button>

    {/* <!-- Collapsible wrapper --> */}
    <div class="collapse navbar-collapse" id="navbarLeftAlignExample">
      {/* <!-- Left links --> */}
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">
              HOME
              </a>
        </li>
        <li class="nav-item">
           {/* <!-- Navbar dropdown --> */}
        <li class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle"
            href="#"
            id="navbarDropdown"
            role="button"
            data-mdb-toggle="dropdown"
            aria-expanded="false"
          >
            ABOUT US
          </a>
          {/* <!-- Dropdown menu --> */}
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li>
              <a class="dropdown-item" href="#">Action</a>
            </li>
            <li>
              <a class="dropdown-item" href="#">Another action</a>
            </li>
            <li><hr class="dropdown-divider" /></li>
            <li>
              <a class="dropdown-item" href="#">Something else here</a>
            </li>
          </ul>
        </li>
        </li>
        {/* <!-- Navbar dropdown --> */}
        <li class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle"
            href="#"
            id="navbarDropdown"
            role="button"
            data-mdb-toggle="dropdown"
            aria-expanded="false"
          >
            ADMISSION
            </a>
          {/* <!-- Dropdown menu --> */}
          <ul className="dropdown-menu" style={{zIndex:1000}} aria-labelledby="navbarDropdown">
            <li>
              <a class="dropdown-item" href="#">Action</a>
            </li>
            <li>
              <a class="dropdown-item" href="#">Another action</a>
            </li>
            <li><hr class="dropdown-divider" /></li>
            <li>
              <a class="dropdown-item" href="#">Something else here</a>
            </li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">
              CURRICULUM
              </a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">
             OUR CAMPUSES
              </a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">
             JOIN US
              </a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">
              CONTACT US
              </a>
        </li>
      </ul>
      {/* <!-- Left links --> */}
    </div>
    {/* <!-- Collapsible wrapper --> */}
  </div>
</nav>
</div>
       </header>
   </div>
    )
}
export default Header;