import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/header'
import Slidesshow from '../components/slideshow'
import Main from '../components/main'
import News from '../components/main'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* <!-- Font Awesome --> */}
<link
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
  rel="stylesheet"
/>
{/* <!-- Google Fonts --\ */}
<link
  href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
  rel="stylesheet"
/>
{/* <!-- MDB --> */}
<link
  href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.css"
  rel="stylesheet"
/>
      </Head>
      <Header />
      <Slidesshow/>
      <News/>
      <footer>
      </footer>
    </div>
  )
}
